"""Tests for the recognizer's ALTER TABLE actions."""

import unittest

from sustained.dialects import Dialects
from sustained.impact.recognizer import (
    recognize,
)
from tests.test_impact_recognizer import (
    MSSQL,
    MYSQL,
    PG,
    RecognizerTestCase,
    action,
)


class AlterTableTestCase(RecognizerTestCase):
    def test_table_options(self):
        parsed = recognize("ALTER TABLE IF EXISTS ONLY app.t DROP COLUMN c")
        self.assertEqual(parsed.table, "app.t")
        self.assertTrue(parsed.options["if_exists"])
        self.assertTrue(parsed.options["only"])

    def test_several_actions_in_order(self):
        parsed = recognize(
            "ALTER TABLE t ADD COLUMN a int, DROP COLUMN b, ALTER COLUMN c SET NOT NULL"
        )
        self.assertEqual(
            [(a.kind, a.column) for a in parsed.actions],
            [("add_column", "a"), ("drop_column", "b"), ("set_not_null", "c")],
        )

    def test_add_column_definition(self):
        added = action(
            "ALTER TABLE t ADD COLUMN IF NOT EXISTS c varchar(20) NOT NULL "
            "DEFAULT 'x' REFERENCES u (id) ON DELETE SET NULL UNIQUE CHECK (c <> '')"
        )
        self.assertEqual(added.kind, "add_column")
        self.assertEqual(added.column, "c")
        options = added.options
        self.assertEqual(options["type"], "varchar(20)")
        self.assertTrue(options["not_null"])
        self.assertEqual(options["default"], "'x'")
        self.assertEqual(options["default_volatility"], "constant")
        self.assertEqual(options["references"], "u")
        self.assertTrue(options["unique"])
        self.assertTrue(options["check"])
        self.assertTrue(options["if_not_exists"])

    def test_add_column_without_the_column_keyword(self):
        self.assertEqual(action("ALTER TABLE t ADD c int").column, "c")

    def test_multi_word_and_array_types(self):
        cases = {
            "timestamp with time zone": "timestamp with time zone",
            "double precision NOT NULL": "double precision",
            "character varying(10)": "character varying(10)",
            "int[] DEFAULT '{}'": "int[]",
            "numeric(10, 2)": "numeric(10, 2)",
            '"my type"': '"my type"',
        }
        for definition, type_sql in cases.items():
            with self.subTest(definition):
                added = action(f"ALTER TABLE t ADD COLUMN c {definition}")
                self.assertEqual(added.options["type"], type_sql)

    def test_serial_identity_and_generated_columns(self):
        self.assertTrue(action("ALTER TABLE t ADD c bigserial").options["serial"])
        identity = action(
            "ALTER TABLE t ADD c int GENERATED BY DEFAULT AS IDENTITY (START 5)"
        ).options
        self.assertEqual(identity["generated"], "identity")
        self.assertTrue(identity["identity"])
        stored = action(
            "ALTER TABLE t ADD c int GENERATED ALWAYS AS (a + b) STORED"
        ).options
        self.assertEqual(stored["generated"], "stored")
        virtual = action("ALTER TABLE t ADD c int AS (a + b) VIRTUAL", MYSQL).options
        self.assertEqual(virtual["generated"], "virtual")
        self.assertTrue(
            action("ALTER TABLE t ADD c INT IDENTITY(1,1)", MSSQL).options["identity"]
        )

    def test_more_column_forms(self):
        keyed = action("ALTER TABLE t ADD c int PRIMARY KEY", PG).options
        self.assertTrue(keyed["primary_key"])
        self.assertEqual(action("ALTER TABLE t ADD c int[3]").options["type"], "int[3]")
        self.assertTrue(
            action("ALTER TABLE t ADD c int AUTO_INCREMENT", MYSQL).options["identity"]
        )
        self.assertEqual(
            action("ALTER TABLE t ALTER COLUMN c SET INVISIBLE", MYSQL).kind,
            "set_storage",
        )
        self.assertUnknown("ALTER TABLE t ADD c int NOT DEFERRABLE", table="t")
        self.assertUnknown("ALTER TABLE t ADD c (int)", table="t")

    def test_malformed_clauses_are_unknown(self):
        for sql, dialect in (
            ("ALTER TABLE t WITH SOMETHING ADD c int", MSSQL),
            ("ALTER TABLE t ADD CONSTRAINT c NOTHING", PG),
            ("ALTER TABLE t ADD FOREIGN KEY (a) REFERENCES u ON DELETE EXPLODE", PG),
            ("ALTER TABLE t CONVERT TO utf8", MYSQL),
            ("ALTER TABLE t,", PG),
            ("ALTER TABLE t ADD c int DEFAULT", PG),
            ("CREATE INDEX ix ON t (a) WITH (= 1)", PG),
        ):
            with self.subTest(sql):
                self.assertUnknown(sql, dialect, table="t")
        self.assertUnknown("ALTER SEQUENCE s RESTART")

    def test_mysql_column_attributes(self):
        added = action(
            "ALTER TABLE t ADD COLUMN c VARCHAR(10) CHARACTER SET utf8mb4 "
            "COLLATE utf8mb4_bin NULL COMMENT 'x' AFTER b",
            MYSQL,
        )
        self.assertFalse(added.options["not_null"])
        self.assertEqual(added.options["position"], "after b")
        self.assertEqual(
            action("ALTER TABLE t ADD c INT FIRST", MYSQL).options["position"], "first"
        )
        updated = action(
            "ALTER TABLE t ADD c TIMESTAMP DEFAULT CURRENT_TIMESTAMP "
            "ON UPDATE CURRENT_TIMESTAMP",
            MYSQL,
        )
        self.assertEqual(updated.options["default"], "CURRENT_TIMESTAMP")

    def test_mssql_not_null_default_with_values(self):
        added = action(
            "ALTER TABLE t ADD c INT NOT NULL CONSTRAINT df DEFAULT 0 WITH VALUES",
            MSSQL,
        )
        self.assertTrue(added.options["not_null"])
        self.assertEqual(added.options["default"], "0")
        self.assertTrue(added.options["with_values"])

    def test_mssql_lists_more_columns_after_one_add_or_drop(self):
        parsed = recognize("ALTER TABLE t ADD a INT, b INT NULL", MSSQL)
        self.assertEqual([a.column for a in parsed.actions], ["a", "b"])
        parsed = recognize("ALTER TABLE t DROP COLUMN a, b", MSSQL)
        self.assertEqual(
            [(a.kind, a.column) for a in parsed.actions],
            [("drop_column", "a"), ("drop_column", "b")],
        )
        self.assertUnknown("ALTER TABLE t ADD a INT, b INT", PG, table="t")

    def test_constraints(self):
        cases = [
            ("ADD CONSTRAINT pk PRIMARY KEY (id)", "primary_key", {"name": "pk"}),
            (
                "ADD CONSTRAINT uq UNIQUE USING INDEX ix_uq",
                "unique",
                {"using_index": "ix_uq"},
            ),
            ("ADD UNIQUE NULLS NOT DISTINCT (a, b)", "unique", {"name": None}),
            (
                "ADD CONSTRAINT fk FOREIGN KEY (a) REFERENCES app.u (id) "
                "ON DELETE CASCADE ON UPDATE NO ACTION MATCH FULL "
                "DEFERRABLE INITIALLY DEFERRED NOT VALID",
                "foreign_key",
                {"references": "app.u", "not_valid": True},
            ),
            ("ADD CHECK (a > 0) NOT VALID", "check", {"not_valid": True}),
            (
                "ADD CONSTRAINT ex EXCLUDE USING gist (r WITH &&)",
                "exclude",
                {"name": "ex"},
            ),
        ]
        for clause, constraint, expected in cases:
            with self.subTest(clause):
                added = action(f"ALTER TABLE t {clause}")
                self.assertEqual(added.kind, "add_constraint")
                self.assertEqual(added.options["constraint"], constraint)
                for key, value in expected.items():
                    self.assertEqual(added.options[key], value)

    def test_mysql_keys_and_indexes(self):
        unique = action("ALTER TABLE t ADD UNIQUE KEY uq_a (a)", MYSQL)
        self.assertEqual(unique.options["name"], "uq_a")
        index = action("ALTER TABLE t ADD INDEX ix_a USING BTREE (a)", MYSQL)
        self.assertEqual(index.kind, "add_index")
        self.assertEqual(index.options["name"], "ix_a")
        fulltext = action("ALTER TABLE t ADD FULLTEXT KEY ft (body)", MYSQL)
        self.assertTrue(fulltext.options["fulltext"])
        fk = action("ALTER TABLE t ADD FOREIGN KEY fk_a (a) REFERENCES u (id)", MYSQL)
        self.assertEqual(fk.options["name"], "fk_a")

    def test_mssql_check_forms(self):
        parsed = recognize(
            "ALTER TABLE t WITH NOCHECK ADD CONSTRAINT ck CHECK (a > 0)", MSSQL
        )
        self.assertTrue(parsed.options["nocheck"])
        self.assertEqual(parsed.actions[0].options["constraint"], "check")
        parsed = recognize("ALTER TABLE t WITH CHECK CHECK CONSTRAINT ck", MSSQL)
        self.assertFalse(parsed.options["nocheck"])
        self.assertEqual(parsed.actions[0].kind, "enable_constraint")
        self.assertEqual(
            action("ALTER TABLE t NOCHECK CONSTRAINT ck", MSSQL).kind,
            "disable_constraint",
        )
        default = action("ALTER TABLE [t] ADD DEFAULT (N'raw') FOR [grade]", MSSQL)
        self.assertEqual((default.kind, default.column), ("set_default", "grade"))

    def test_drops(self):
        cases = [
            ("DROP CONSTRAINT IF EXISTS ck CASCADE", "drop_constraint", None),
            ("DROP FOREIGN KEY fk", "drop_constraint", None),
            ("DROP PRIMARY KEY", "drop_constraint", None),
            ("DROP CHECK ck", "drop_constraint", None),
            ("DROP INDEX ix", "drop_index", None),
            ("DROP KEY ix", "drop_index", None),
            ("DROP COLUMN IF EXISTS c RESTRICT", "drop_column", "c"),
            ("DROP c", "drop_column", "c"),
        ]
        for clause, kind, column in cases:
            with self.subTest(clause):
                dropped = action(f"ALTER TABLE t {clause}", MYSQL)
                self.assertEqual((dropped.kind, dropped.column), (kind, column))
        self.assertUnknown("ALTER TABLE t DROP PARTITION p1", MYSQL, table="t")

    def test_alter_column_forms(self):
        cases = [
            ("ALTER COLUMN c TYPE bigint", "alter_column_type"),
            ("ALTER c SET DATA TYPE text", "alter_column_type"),
            ("ALTER COLUMN c SET NOT NULL", "set_not_null"),
            ("ALTER COLUMN c DROP NOT NULL", "drop_not_null"),
            ("ALTER COLUMN c SET DEFAULT now()", "set_default"),
            ("ALTER COLUMN c DROP DEFAULT", "drop_default"),
            ("ALTER COLUMN c SET STATISTICS 500", "set_statistics"),
            ("ALTER COLUMN c SET STORAGE EXTERNAL", "set_storage"),
        ]
        for clause, kind in cases:
            with self.subTest(clause):
                altered = action(f"ALTER TABLE t {clause}")
                self.assertEqual((altered.kind, altered.column), (kind, "c"))

    def test_type_change_details(self):
        altered = action(
            'ALTER TABLE t ALTER COLUMN "c" TYPE varchar(20) COLLATE "C" '
            "USING c::varchar(20)"
        )
        self.assertEqual(altered.options["type"], "varchar(20)")
        self.assertEqual(altered.options["collate"], "C")
        self.assertEqual(altered.options["using"], "c::varchar(20)")
        self.assertIsNone(action("ALTER TABLE t ALTER c TYPE int").options["using"])

    def test_set_default_is_classified(self):
        altered = action("ALTER TABLE t ALTER COLUMN c SET DEFAULT gen_random_uuid()")
        self.assertEqual(altered.options["default_volatility"], "volatile")

    def test_mssql_alter_column_restates_the_column(self):
        altered = action(
            "ALTER TABLE [t] ALTER COLUMN [c] NVARCHAR(20) COLLATE Latin1_General_CI_AS "
            "NOT NULL WITH (ONLINE = ON)",
            MSSQL,
        )
        self.assertEqual(altered.kind, "alter_column")
        self.assertEqual(altered.options["type"], "NVARCHAR(20)")
        self.assertTrue(altered.options["not_null"])
        self.assertEqual(altered.options["with"], {"ONLINE": "ON"})

    def test_unread_alter_column_is_unknown(self):
        for clause in (
            "ALTER COLUMN c SET COMPRESSION lz4",
            "ALTER COLUMN c DROP IDENTITY",
            "ALTER CONSTRAINT fk DEFERRABLE",
        ):
            with self.subTest(clause):
                self.assertUnknown(f"ALTER TABLE t {clause}", table="t")

    def test_mysql_modify_and_change(self):
        modified = action(
            "ALTER TABLE t MODIFY COLUMN c VARCHAR(50) NOT NULL AFTER b", MYSQL
        )
        self.assertEqual(modified.kind, "modify_column")
        self.assertEqual(modified.options["type"], "VARCHAR(50)")
        changed = action("ALTER TABLE t CHANGE old new INT NULL", MYSQL)
        self.assertEqual((changed.kind, changed.column), ("change_column", "old"))
        self.assertEqual(changed.options["new"], "new")

    def test_renames(self):
        cases = [
            ("RENAME COLUMN a TO b", "rename_column", "a"),
            ("RENAME a TO b", "rename_column", "a"),
            ("RENAME TO u", "rename_to", None),
            ("RENAME AS u", "rename_to", None),
            ("RENAME CONSTRAINT a TO b", "rename_constraint", None),
            ("RENAME INDEX a TO b", "rename_index", None),
        ]
        for clause, kind, column in cases:
            with self.subTest(clause):
                renamed = action(f"ALTER TABLE t {clause}", MYSQL)
                self.assertEqual((renamed.kind, renamed.column), (kind, column))
                self.assertIn(renamed.options["new"], ("b", "u"))

    def test_partitions(self):
        attached = action(
            "ALTER TABLE p ATTACH PARTITION p_2026 FOR VALUES FROM ('2026-01-01') "
            "TO ('2027-01-01')"
        )
        self.assertEqual(attached.kind, "attach_partition")
        self.assertEqual(attached.options["partition"], "p_2026")
        self.assertEqual(
            action("ALTER TABLE p ATTACH PARTITION d DEFAULT").kind, "attach_partition"
        )
        detached = action("ALTER TABLE p DETACH PARTITION p_2026 CONCURRENTLY")
        self.assertTrue(detached.options["concurrently"])
        self.assertTrue(
            action("ALTER TABLE p DETACH PARTITION x FINALIZE").options["finalize"]
        )
        self.assertUnknown("ALTER TABLE p ATTACH PARTITION x", table="p")

    def test_table_level_actions(self):
        cases = [
            ("VALIDATE CONSTRAINT fk", "validate_constraint"),
            ("SET TABLESPACE fast", "set_tablespace"),
            ("SET LOGGED", "set_logged"),
            ("SET UNLOGGED", "set_unlogged"),
            ("SET SCHEMA archive", "set_schema"),
            ("SET (fillfactor = 70)", "set_parameters"),
            ("OWNER TO app", "owner_to"),
            ("ENABLE TRIGGER trg", "enable_trigger"),
            ("DISABLE TRIGGER ALL", "disable_trigger"),
            ("ENABLE ALWAYS TRIGGER trg", "enable_trigger"),
            ("ENABLE ROW LEVEL SECURITY", "row_security"),
        ]
        for clause, kind in cases:
            with self.subTest(clause):
                self.assertEqual(action(f"ALTER TABLE t {clause}").kind, kind)
        for clause in ("SET WITHOUT CLUSTER", "ENABLE RULE r"):
            with self.subTest(clause):
                self.assertUnknown(f"ALTER TABLE t {clause}", table="t")

    def test_mysql_table_options(self):
        parsed = recognize(
            "ALTER TABLE t ADD COLUMN c INT, ALGORITHM=INSTANT, LOCK = NONE", MYSQL
        )
        self.assertEqual(parsed.options["algorithm"], "INSTANT")
        self.assertEqual(parsed.options["lock"], "NONE")
        self.assertEqual([a.kind for a in parsed.actions], ["add_column"])
        self.assertEqual(action("ALTER TABLE t ENGINE = InnoDB", MYSQL).kind, "engine")
        converted = action(
            "ALTER TABLE t CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin", MYSQL
        )
        self.assertEqual(converted.options["charset"], "utf8mb4")
        self.assertEqual(action("ALTER TABLE t FORCE", MYSQL).kind, "force")

    def test_an_alter_with_only_table_options_is_unknown(self):
        self.assertUnknown("ALTER TABLE t ALGORITHM=INPLACE", MYSQL, table="t")

    def test_unknown_action_keeps_the_table(self):
        parsed = self.assertUnknown(
            "ALTER TABLE app.t ADD COLUMN a int, CLUSTER ON ix", table="app.t"
        )
        self.assertIn("CLUSTER", parsed.options["reason"])

    def test_athena_add_columns_is_unknown(self):
        self.assertUnknown(
            "ALTER TABLE `t` ADD COLUMNS (`note` STRING)", Dialects.ATHENA, table="t"
        )


if __name__ == "__main__":
    unittest.main()
