from typing import TYPE_CHECKING, Optional

from .base import Compiler

if TYPE_CHECKING:
    from sustained.schema import ColumnDef, ColumnState


class PostgresCompiler(Compiler):
    _IDENT_QUOTES = ('"', '"')
    _native_ilike = True
    _distinct_on = True
    _for_update = True
    # Postgres takes a bare OFFSET and rejects a negative LIMIT.
    _bare_offset = True
    _comment_on_column = True
    _typed_temporal_literals = True
    _ALTER_TYPE_KEYWORD = "TYPE"
    supports_partial_index = True

    def stores_column_comments(self) -> bool:
        return True

    def placeholder(self) -> str:
        # The %s style used by psycopg and psycopg2.
        return "%s"

    def escapes_percent(self) -> bool:
        # psycopg and psycopg2 read %% as one literal % sign.
        return True

    def compile_binary_literal(self, hex_text: str) -> str:
        # decode() reads the same whatever standard_conforming_strings says.
        return f"decode('{hex_text}', 'hex')"

    def parenthesized_set_members(self) -> bool:
        return True

    _TYPE_MAP = {**Compiler._TYPE_MAP, "JSON": "JSONB", "BINARY": "BYTEA"}

    def compile_identity(self) -> str:
        return "GENERATED BY DEFAULT AS IDENTITY"

    def enum_strategy(self) -> str:
        return "native"

    def compile_add_enum_value(self, name: str, value: str) -> str:
        # Runs inside a transaction from Postgres 12 on, so a rehearsal
        # can roll it back. There is no DROP VALUE to reverse it with.
        return (
            f"ALTER TYPE {self.quote_identifier(name)} "
            f"ADD VALUE {self.format_value(value)}"
        )

    def supports_alter_column(self) -> bool:
        return True

    def alter_type_keeps_default(self) -> bool:
        # The server casts the default to the new type itself and
        # refuses the change when that cast is not automatic, so the
        # default comes off before the change and goes back on after it.
        return False

    def lifted_default_sql(
        self, model_default_sql: Optional[str], live_default_sql: str
    ) -> str:
        # pg_attrdef spells a default with a cast to the old type, as in
        # '7'::text, so the model's default goes back on when the model
        # declares one.
        return live_default_sql if model_default_sql is None else model_default_sql

    def migration_lock_sql(self, name: str) -> "list[str]":
        # Session-scoped and reentrant, so a sync() that calls up() locks
        # and unlocks in balanced pairs. Released on disconnect.
        return [f"SELECT pg_advisory_lock(hashtext({self.format_value(name)}))"]

    def migration_unlock_sql(self, name: str) -> "list[str]":
        return [f"SELECT pg_advisory_unlock(hashtext({self.format_value(name)}))"]
